name: Build & Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.9'

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@v0.4.4

      - name: Build Caddy
        run: |
          mkdir ~/build
          cd ~/build
          GOARCH=amd64 xcaddy build --output caddy-${{ github.ref_name }}-linux-amd64 ${{ github.ref_name }} --with github.com/caddy-dns/cloudflare@v0.2.1
          GOARCH=arm64 xcaddy build --output caddy-${{ github.ref_name }}-linux-arm64 ${{ github.ref_name }} --with github.com/caddy-dns/cloudflare@v0.2.1
          GOARCH=loong64 xcaddy build --output caddy-${{ github.ref_name }}-linux-loong64 ${{ github.ref_name }} --with github.com/caddy-dns/cloudflare@v0.2.1
          GOARCH=mips64le xcaddy build --output caddy-${{ github.ref_name }}-linux-mips64le ${{ github.ref_name }} --with github.com/caddy-dns/cloudflare@v0.2.1
          GOARCH=ppc64le xcaddy build --output caddy-${{ github.ref_name }}-linux-ppc64le ${{ github.ref_name }} --with github.com/caddy-dns/cloudflare@v0.2.1
          GOARCH=riscv64 xcaddy build --output caddy-${{ github.ref_name }}-linux-riscv64 ${{ github.ref_name }} --with github.com/caddy-dns/cloudflare@v0.2.1
          cd ~/build
          zstd *
          sha256sum *.zst > SHA256SUMS.txt
          cat SHA256SUMS.txt

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run:
          gh release -R ${{ github.repository }} create -F README.md ${{ github.ref_name }} -t ${{ github.ref_name }} ~/build/SHA256SUMS.txt ~/build/*zst
